name: WincherToldU
author: Wincher Hoo
baseurl: /WincherToldYou
description: Wincher's sharing
github: https://github.com/Wincher
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: wincher.hoo@gmail.com
location: 39°54′13.44N 116°23′30.15E

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
